require 'mkmf'

$CFLAGS << ' -DNK_INCLUDE_VERTEX_BUFFER_OUTPUT=1'
$CFLAGS << ' -DNK_INCLUDE_FONT_BAKING=1'
$CFLAGS << ' -DNK_INCLUDE_DEFAULT_FONT=1'
$CFLAGS << ' -DNK_INCLUDE_COMMAND_USERDATA=1'
$CFLAGS << ' -DNK_BUTTON_TRIGGER_ON_RELEASE=1'
$CFLAGS << ' -DNK_ZERO_COMMAND_MEMORY=1'
$CFLAGS << ' -DNK_INCLUDE_FIXED_TYPES=1'
$CFLAGS << ' -DNK_INCLUDE_DEFAULT_ALLOCATOR=1'
$CFLAGS << ' -DNK_INCLUDE_STANDARD_IO=1'

create_makefile('nuklear_renderer_opengl4')
